package com.example.trello_wannabe;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/signup") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String email, @RequestParam String password){

        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();

        n.setEmail(email);
        n.setPassword(password);
        userRepository.save(n);
        return "Saved";

    }
    @PostMapping(path="/login")
    public @ResponseBody Iterable<User> getAllUsers(@RequestParam String email, @RequestParam String password) {

        //Procedure to find user by email

        //userRepository.findAll();
        return userRepository.findAll();
    }
}